/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement; // Added this line to import Statement class

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Dosen extends javax.swing.JFrame {

    /**
     * Creates new form Mahasiswa
     */
    public Dosen() {
        initComponents();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDosenMouseClicked(evt);

            }
        });
        
        loadDosenData();

    }
    
    private void loadDosenData() {
    String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Bersihkan tabel sebelum memuat data

    try {
        Connection conn = DriverManager.getConnection(url, user, password);
        Statement stmt = conn.createStatement(); // Using Statement class
        String sql = "SELECT Nip, Nama_Dosen FROM dosen";
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            String nip = rs.getString("Nip");
            String namaDosen = rs.getString("Nama_Dosen");
            model.addRow(new Object[]{nip, namaDosen});
        }

        rs.close();
        stmt.close(); // Closing Statement
        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error menghubungkan ke database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMatakuliah = new javax.swing.JLabel();
        btnDosen = new javax.swing.JLabel();
        btnMahasiswa = new javax.swing.JLabel();
        btnPerkuliahan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JDataDosen = new javax.swing.JLabel();
        JNip = new javax.swing.JLabel();
        jtfNip = new javax.swing.JTextField();
        JNamaDosen = new javax.swing.JLabel();
        jtfNamaDosen = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 112, 107));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnMatakuliah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMatakuliah.setForeground(new java.awt.Color(255, 255, 255));
        btnMatakuliah.setText("Matakuliah");
        btnMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMatakuliahMouseClicked(evt);
            }
        });

        btnDosen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnDosen.setText("Dosen");
        btnDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDosenMouseClicked(evt);
            }
        });

        btnMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnMahasiswa.setText("Mahasiswa");
        btnMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMahasiswaMouseClicked(evt);
            }
        });

        btnPerkuliahan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPerkuliahan.setForeground(new java.awt.Color(255, 255, 255));
        btnPerkuliahan.setText("Perkuliahan");
        btnPerkuliahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerkuliahanMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("____________");

        jButton4.setBackground(new java.awt.Color(204, 51, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Logout");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMatakuliah)
                            .addComponent(btnDosen)
                            .addComponent(btnMahasiswa)
                            .addComponent(btnPerkuliahan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton4)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addComponent(btnMatakuliah)
                .addGap(18, 18, 18)
                .addComponent(btnDosen)
                .addGap(18, 18, 18)
                .addComponent(btnMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(btnPerkuliahan)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nip", "Nama Dosen"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        JDataDosen.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JDataDosen.setForeground(new java.awt.Color(0, 112, 107));
        JDataDosen.setText("Data Dosen");

        JNip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JNip.setText("Nip");

        jtfNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNipActionPerformed(evt);
            }
        });

        JNamaDosen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JNamaDosen.setText("Nama Dosen");

        jtfNamaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNamaDosenActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 204, 51));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(JDataDosen)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JNip)
                                    .addComponent(jtfNip, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JNamaDosen))))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(271, 271, 271))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDataDosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNip)
                    .addComponent(JNamaDosen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void jtfNipActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jtfNamaDosenActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda
    String nip = jtfNip.getText();
    String namaDosen = jtfNamaDosen.getText();

    if (nip.isEmpty() || namaDosen.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "UPDATE dosen SET Nama_Dosen = ? WHERE Nip = ?";

    try (Connection conn = DriverManager.getConnection(url, user, password);
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        pstmt.setString(1, namaDosen);
        pstmt.setString(2, nip);
        int affectedRows = pstmt.executeUpdate();
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(this, "Data dosen berhasil diperbarui.");
            loadDosenData(); // Memuat ulang data dosen
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada perubahan data. Pastikan NIP dosen sudah benar.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error memperbarui data dosen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
    }
    clearFields();
    }                                       


    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda
    String nip = jtfNip.getText();
    String namaDosen = jtfNamaDosen.getText();

    if (nip.isEmpty() || namaDosen.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "INSERT INTO dosen (Nip, Nama_Dosen) VALUES (?, ?)";

    try (Connection conn = DriverManager.getConnection(url, user, password);
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        pstmt.setString(1, nip);
        pstmt.setString(2, namaDosen);
        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data dosen berhasil ditambahkan.");
        loadDosenData(); // Memuat ulang data dosen
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error menambahkan data dosen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
       
    }
    clearFields();
    }                                         


    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda
    String nip = jtfNip.getText();

    if (nip.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "DELETE FROM dosen WHERE Nip = ?";

    try (Connection conn = DriverManager.getConnection(url, user, password);
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        pstmt.setString(1, nip);
        int affectedRows = pstmt.executeUpdate();
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(this, "Data dosen berhasil dihapus.");
            loadDosenData(); // Memuat ulang data dosen
        } else {
            JOptionPane.showMessageDialog(this, "Data dosen tidak ditemukan.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error menghapus data dosen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
    }
    clearFields();
    }                                        



    private void btnMatakuliahMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        Matakuliah matakuliah= new Matakuliah();
        matakuliah.setVisible(true);
        this.dispose();
    }                                          


    private void btnDosenMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void btnMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        Mahasiswa mahasiswa = new Mahasiswa();
        mahasiswa.setVisible(true);
        this.dispose();
    }                                         


    private void btnPerkuliahanMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        Perkuliahan perkuliahan = new Perkuliahan();
        perkuliahan.setVisible(true);
        this.dispose();
    }                                           


    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }                                     

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }
    private void tabelDosenMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // Mendapatkan model tabel
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
        // Mendapatkan baris yang dipilih

        int selectedRowIndex = jTable1.getSelectedRow();
    
        // Mengambil data dari baris yang dipilih dan menampilkannya di field teks
        jtfNip.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jtfNamaDosen.setText(model.getValueAt(selectedRowIndex, 1).toString());
    }
    private void clearFields() {
        jtfNip.setText("");
        jtfNamaDosen.setText("");
    }
                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel JDataDosen;
    private javax.swing.JLabel JNamaDosen;
    private javax.swing.JLabel JNip;
    private javax.swing.JLabel btnDosen;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel btnMahasiswa;
    private javax.swing.JLabel btnMatakuliah;
    private javax.swing.JLabel btnPerkuliahan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtfNamaDosen;
    private javax.swing.JTextField jtfNip;
    // End of variables declaration                   
}
