/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Mahasiswa extends javax.swing.JFrame {

    public Mahasiswa() {
        initComponents();
        loadMahasiswaData();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        
    }
    private void loadMahasiswaData() {
        try {
            // Membuat koneksi ke database
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_akademik", "root", "");
            Statement stmt = con.createStatement();
            
            // Query untuk mengambil data mahasiswa
            String sql = "SELECT Nim, Nama_Mhs, Tgl_Lahir, Alamat, Jenis_Kelamin FROM mahasiswa";
            ResultSet rs = stmt.executeQuery(sql);
            
            // Mengatur model tabel dan mengisinya dengan data dari ResultSet
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Mengosongkan tabel sebelum diisi
            
            while (rs.next()) {
                // Menambahkan baris ke tabel
                model.addRow(new Object[]{
                    rs.getString("Nim"),
                    rs.getString("Nama_Mhs"),
                    rs.getDate("Tgl_Lahir"),
                    rs.getString("Alamat"),
                    rs.getString("Jenis_Kelamin")
                });
            }
            
            // Menutup koneksi
            rs.close();
            stmt.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMatakuliah = new javax.swing.JLabel();
        btnDosen = new javax.swing.JLabel();
        btnMahasiswa = new javax.swing.JLabel();
        btnPerkuliahan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JDataMahasiswa = new javax.swing.JLabel();
        JNim = new javax.swing.JLabel();
        jtfNim = new javax.swing.JTextField();
        JNamaMahasiswa = new javax.swing.JLabel();
        JTanggalLahir = new javax.swing.JLabel();
        jtfNamaMahasiswa = new javax.swing.JTextField();
        jtfTanggalLahir = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        JAlamat = new javax.swing.JLabel();
        JJenisKelamin = new javax.swing.JLabel();
        jtfAlamat = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 112, 107));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnMatakuliah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMatakuliah.setForeground(new java.awt.Color(255, 255, 255));
        btnMatakuliah.setText("Matakuliah");
        btnMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMatakuliahMouseClicked(evt);
            }
        });

        btnDosen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnDosen.setText("Dosen");
        btnDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDosenMouseClicked(evt);
            }
        });

        btnMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnMahasiswa.setText("Mahasiswa");
        btnMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMahasiswaMouseClicked(evt);
            }
        });

        btnPerkuliahan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPerkuliahan.setForeground(new java.awt.Color(255, 255, 255));
        btnPerkuliahan.setText("Perkuliahan");
        btnPerkuliahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerkuliahanMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("____________");

        btnLogout.setBackground(new java.awt.Color(204, 51, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMatakuliah)
                            .addComponent(btnDosen)
                            .addComponent(btnMahasiswa)
                            .addComponent(btnPerkuliahan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnLogout)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addComponent(btnMatakuliah)
                .addGap(18, 18, 18)
                .addComponent(btnDosen)
                .addGap(18, 18, 18)
                .addComponent(btnMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(btnPerkuliahan)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nim", "Nama Mahasiswa", "Tanggal Lahir", "Alamat", "Jenis Kelamin"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        JDataMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JDataMahasiswa.setForeground(new java.awt.Color(0, 112, 107));
        JDataMahasiswa.setText("Data Mahasiswa");

        JNim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JNim.setText("Nim");

        jtfNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNimActionPerformed(evt);
            }
        });

        JNamaMahasiswa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JNamaMahasiswa.setText("Nama Mahasiswa");

        JTanggalLahir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JTanggalLahir.setText("Tanggal Lahir");

        jtfNamaMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNamaMahasiswaActionPerformed(evt);
            }
        });

        jtfTanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTanggalLahirActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 204, 51));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        JAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JAlamat.setText("Alamat");

        JJenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JJenisKelamin.setText("Jenis Kelamin");

        jtfAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAlamatActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Laki-laki");

        jCheckBox2.setText("Perempuan");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1)
                            .addComponent(JDataMahasiswa)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JNim)
                                    .addComponent(jtfNim, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JAlamat)
                                    .addComponent(jtfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JNamaMahasiswa))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTanggalLahir)
                                            .addComponent(jtfTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JJenisKelamin)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(271, 271, 271))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDataMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNim)
                    .addComponent(JNamaMahasiswa)
                    .addComponent(JTanggalLahir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JAlamat)
                    .addComponent(JJenisKelamin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void jtfNimActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jtfNamaMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void jtfTanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String nim = jtfNim.getText();
    String nama = jtfNamaMahasiswa.getText();
    String tanggalLahir = jtfTanggalLahir.getText(); // Pastikan format tanggal sesuai dengan yang diharapkan oleh database
    String alamat = jtfAlamat.getText();
    String jenisKelamin = jCheckBox1.isSelected() ? "Laki-laki" : "Perempuan";

    if (nim.isEmpty() || nama.isEmpty() || tanggalLahir.isEmpty() || alamat.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
        return;
    }

    Connection con = null;
    Statement stmt = null;

    try {
        // Membuat koneksi ke database
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_akademik", "root", "");
        stmt = con.createStatement();

        // Query untuk mengupdate data
        String sql = "UPDATE mahasiswa SET Nama_Mhs='" + nama + "', Tgl_Lahir='" + tanggalLahir + 
                     "', Alamat='" + alamat + "', Jenis_Kelamin='" + jenisKelamin + "' WHERE Nim='" + nim + "'";

        // Eksekusi query
        stmt.executeUpdate(sql);

        // Menampilkan dialog jika berhasil
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui");

        // Memuat ulang data mahasiswa
        loadMahasiswaData();
    } catch (Exception e) {
        e.printStackTrace();
        // Menampilkan dialog jika terjadi kesalahan
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } finally {
        try {
            // Menutup koneksi
            if (stmt != null) stmt.close();
            if (con != null) con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    clearData();
    }                                       


    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String nim = jtfNim.getText();
        String nama = jtfNamaMahasiswa.getText();
        String tanggalLahir = jtfTanggalLahir.getText(); // Pastikan format tanggal sesuai dengan yang diharapkan oleh database
        String alamat = jtfAlamat.getText();
        String jenisKelamin = jCheckBox1.isSelected() ? "Laki-laki" : "Perempuan";

        if (nim.isEmpty() || nama.isEmpty() || tanggalLahir.isEmpty() || alamat.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
            return;
        }
    
        Connection con = null;
        Statement stmt = null;
    
        try {
            // Membuat koneksi ke database
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_akademik", "root", "");
            stmt = con.createStatement();
    
            // Query untuk menambahkan data
            String sql = "INSERT INTO mahasiswa (Nim, Nama_Mhs, Tgl_Lahir, Alamat, Jenis_Kelamin) VALUES ('" 
                         + nim + "', '" + nama + "', '" + tanggalLahir + "', '" + alamat + "', '" + jenisKelamin + "')";
    
            // Eksekusi query
            stmt.executeUpdate(sql);
    
            // Menampilkan dialog jika berhasil
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");
    
            // Memuat ulang data mahasiswa
            loadMahasiswaData();
        } catch (Exception e) {
            e.printStackTrace();
            // Menampilkan dialog jika terjadi kesalahan
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        } finally {
            try {
                // Menutup koneksi
                if (stmt != null) stmt.close();
                if (con != null) con.close();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        clearData();
    }                                         


    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String nim = jtfNim.getText(); // Mengambil NIM dari text field

        if (nim.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
            return;
        }

    Connection con = null;
    Statement stmt = null;

    try {
        // Membuat koneksi ke database
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_akademik", "root", "");
        stmt = con.createStatement();

        // Query untuk menghapus data
        String sql = "DELETE FROM mahasiswa WHERE Nim='" + nim + "'";

        // Eksekusi query
        stmt.executeUpdate(sql);

        // Menampilkan dialog jika berhasil
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

        // Memuat ulang data mahasiswa
        loadMahasiswaData();
    } catch (Exception e) {
        e.printStackTrace();
        // Menampilkan dialog jika terjadi kesalahan
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } finally {
        try {
            // Menutup koneksi
            if (stmt != null) stmt.close();
            if (con != null) con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    clearData();
    }                                        


    private void jtfAlamatActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnMatakuliahMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        Matakuliah matakuliah = new Matakuliah();
        matakuliah.setVisible(true);
        this.dispose();
    }                                          


    private void btnDosenMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        Dosen dosen = new Dosen();
        dosen.setVisible(true);
        this.dispose();
    }                                     


    private void btnMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnPerkuliahanMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        Perkuliahan perkuliahan = new Perkuliahan();
        perkuliahan.setVisible(true);
        this.dispose();
    }                                           


    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }                                      

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }
    private void clearData() {
        jtfNim.setText("");
        jtfNamaMahasiswa.setText("");
        jtfTanggalLahir.setText("");
        jtfAlamat.setText("");
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        // Mendapatkan model dari tabel
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
        // Mendapatkan indeks baris yang dipilih
        int selectedRowIndex = jTable1.getSelectedRow();
    
        // Mengatur nilai dari tabel ke dalam field teks
        jtfNim.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jtfNamaMahasiswa.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jtfTanggalLahir.setText(model.getValueAt(selectedRowIndex, 2).toString());
        jtfAlamat.setText(model.getValueAt(selectedRowIndex, 3).toString());
        
        // Mengatur checkbox untuk jenis kelamin
        String jenisKelamin = model.getValueAt(selectedRowIndex, 4).toString();
        if (jenisKelamin.equals("Laki-laki")) {
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(false);
        } else {
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(true);
        }
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel JAlamat;
    private javax.swing.JLabel JDataMahasiswa;
    private javax.swing.JLabel JJenisKelamin;
    private javax.swing.JLabel JNamaMahasiswa;
    private javax.swing.JLabel JNim;
    private javax.swing.JLabel JTanggalLahir;
    private javax.swing.JLabel btnDosen;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel btnMahasiswa;
    private javax.swing.JLabel btnMatakuliah;
    private javax.swing.JLabel btnPerkuliahan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtfAlamat;
    private javax.swing.JTextField jtfNamaMahasiswa;
    private javax.swing.JTextField jtfNim;
    private javax.swing.JTextField jtfTanggalLahir;
    // End of variables declaration                   
}


