/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Matakuliah extends javax.swing.JFrame {

    public Matakuliah() {
        initComponents();
        loadMatakuliahData();
        tabelDataMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMatakuliahMouseClicked(evt);
            }
        });
    }

    private void loadMatakuliahData() {
        String url = "jdbc:mysql://localhost:3306/db_akademik";
        String user = "root"; // Ganti dengan username database Anda
        String password = ""; // Ganti dengan password database Anda

        DefaultTableModel model = (DefaultTableModel) tabelDataMatakuliah.getModel();
        model.setRowCount(0); // Bersihkan tabel sebelum memuat data

        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT Kode_MK, Nama_MK, sks FROM matakuliah";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String kode = rs.getString("Kode_MK");
                String nama = rs.getString("Nama_MK");
                int sks = rs.getInt("sks");
                model.addRow(new Object[]{kode, nama, sks});
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error menghubungkan ke database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMatakuliah = new javax.swing.JLabel();
        btnDosen = new javax.swing.JLabel();
        btnMahasiswa = new javax.swing.JLabel();
        btnPerkuliahan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataMatakuliah = new javax.swing.JTable();
        LDataMatakuliah = new javax.swing.JLabel();
        JKodeMatakuliah = new javax.swing.JLabel();
        jtfKodeMatakuliah = new javax.swing.JTextField();
        JNamaMatakuliah = new javax.swing.JLabel();
        JSks = new javax.swing.JLabel();
        jtfSks = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jcbNamaMatakuliah = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 112, 107));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnMatakuliah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMatakuliah.setForeground(new java.awt.Color(255, 255, 255));
        btnMatakuliah.setText("Matakuliah");
        btnMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMatakuliahMouseClicked(evt);
            }
        });

        btnDosen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnDosen.setText("Dosen");
        btnDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDosenMouseClicked(evt);
            }
        });

        btnMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnMahasiswa.setText("Mahasiswa");
        btnMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMahasiswaMouseClicked(evt);
            }
        });

        btnPerkuliahan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPerkuliahan.setForeground(new java.awt.Color(255, 255, 255));
        btnPerkuliahan.setText("Perkuliahan");
        btnPerkuliahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerkuliahanMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("____________");

        btnLogout.setBackground(new java.awt.Color(204, 51, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMatakuliah)
                            .addComponent(btnDosen)
                            .addComponent(btnMahasiswa)
                            .addComponent(btnPerkuliahan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnLogout)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addComponent(btnMatakuliah)
                .addGap(18, 18, 18)
                .addComponent(btnDosen)
                .addGap(18, 18, 18)
                .addComponent(btnMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(btnPerkuliahan)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelDataMatakuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Matakuliah", "Nama Matakuliah", "Sks"
            }
        ));
        jScrollPane1.setViewportView(tabelDataMatakuliah);

        LDataMatakuliah.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LDataMatakuliah.setForeground(new java.awt.Color(0, 112, 107));
        LDataMatakuliah.setText("Data Matakuliah");

        JKodeMatakuliah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JKodeMatakuliah.setText("Kode Matakuliah");

        jtfKodeMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKodeMatakuliahActionPerformed(evt);
            }
        });

        JNamaMatakuliah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JNamaMatakuliah.setText("Nama Matakuliah");

        JSks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JSks.setText("Sks");

        jtfSks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSksActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 204, 51));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jcbNamaMatakuliah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metode Pengembangan Perangkat Lunak", "Pemrograman Berbasis Web", "Sistem Informasi", "Teknologi Informasi", "Pemrograman Berbasis Objek", "Agama", "Analisis Perancangan Perangkat Lunak", "Struktur Data" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1)
                            .addComponent(LDataMatakuliah)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JKodeMatakuliah)
                                    .addComponent(jtfKodeMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JNamaMatakuliah)
                                    .addComponent(jcbNamaMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JSks)
                                    .addComponent(jtfSks, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(271, 271, 271))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LDataMatakuliah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JKodeMatakuliah)
                    .addComponent(JNamaMatakuliah)
                    .addComponent(JSks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfKodeMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbNamaMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void jtfKodeMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void jtfSksActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String kodeMK = jtfKodeMatakuliah.getText();
        if (kodeMK.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    String namaMK = jcbNamaMatakuliah.getSelectedItem().toString();
    int sks = Integer.parseInt(jtfSks.getText());
    String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda

    Connection conn = null;
    Statement stmt = null;

    try {
        conn = DriverManager.getConnection(url, user, password);
        stmt = conn.createStatement();
        String sql = "UPDATE matakuliah SET Nama_MK='" + namaMK + "', Sks=" + sks + " WHERE Kode_MK='" + kodeMK + "'";
        stmt.executeUpdate(sql);
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error memperbarui data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (stmt != null) stmt.close();
            if (conn != null) conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error menutup koneksi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    loadMatakuliahData(); // Memuat ulang data matakuliah
    clearFields();
    }                                       

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String kodeMK = jtfKodeMatakuliah.getText();
    String namaMK = jcbNamaMatakuliah.getSelectedItem().toString();
    String sksText = jtfSks.getText();

    if (kodeMK.isEmpty() || namaMK.isEmpty() || sksText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Hentikan eksekusi lebih lanjut jika ada field yang kosong
    }
    int sks = Integer.parseInt(jtfSks.getText());
    String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda

    Connection conn = null;
    Statement stmt = null;

    try {
        conn = DriverManager.getConnection(url, user, password);
        stmt = conn.createStatement();
        String sql = "INSERT INTO matakuliah (Kode_MK, Nama_MK, Sks) VALUES ('" + kodeMK + "', '" + namaMK + "', " + sks + ")";
        stmt.executeUpdate(sql);
        JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error menambahkan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (stmt != null) stmt.close();
            if (conn != null) conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error menutup koneksi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    loadMatakuliahData(); // Memuat ulang data matakuliah
    clearFields();
    }                                         


    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String kodeMK = jtfKodeMatakuliah.getText();
        if (kodeMK.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda

    Connection conn = null;
    Statement stmt = null;

    int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (response == JOptionPane.YES_OPTION) {
        try {
            conn = DriverManager.getConnection(url, user, password);
            stmt = conn.createStatement();
            String sql = "DELETE FROM matakuliah WHERE Kode_MK='" + kodeMK + "'";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error menutup koneksi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadMatakuliahData(); // Memuat ulang data matakuliah
        clearFields();
    }
    }                                        


    private void btnMatakuliahMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btnDosenMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        Dosen dosen = new Dosen();
        dosen.setVisible(true);
        this.dispose();
    }                                     


    private void btnMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        Mahasiswa mahasiswa = new Mahasiswa();
        mahasiswa.setVisible(true);
        this.dispose();
    }                                         


    private void btnPerkuliahanMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        Perkuliahan perkuliahan = new Perkuliahan();
        perkuliahan.setVisible(true);
        this.dispose();
    }                                           


    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }                                      

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }  
    private void tabelDataMatakuliahMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // Mendapatkan model tabel
        DefaultTableModel model = (DefaultTableModel) tabelDataMatakuliah.getModel();
    
        // Mendapatkan baris yang dipilih
        int selectedRowIndex = tabelDataMatakuliah.getSelectedRow();
    
        // Mengambil data dari baris yang dipilih dan menampilkannya di field teks
        jtfKodeMatakuliah.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jcbNamaMatakuliah.setSelectedItem(model.getValueAt(selectedRowIndex, 1).toString());
        jtfSks.setText(model.getValueAt(selectedRowIndex, 2).toString());
    } 
    private void clearFields() {
        jtfKodeMatakuliah.setText("");
        jcbNamaMatakuliah.setSelectedIndex(0); // Mengatur kembali ke item pertama dalam combobox
        jtfSks.setText("");
    }
                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matakuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel JKodeMatakuliah;
    private javax.swing.JLabel JNamaMatakuliah;
    private javax.swing.JLabel JSks;
    private javax.swing.JLabel LDataMatakuliah;
    private javax.swing.JLabel btnDosen;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel btnMahasiswa;
    private javax.swing.JLabel btnMatakuliah;
    private javax.swing.JLabel btnPerkuliahan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcbNamaMatakuliah;
    private javax.swing.JTextField jtfKodeMatakuliah;
    private javax.swing.JTextField jtfSks;
    private javax.swing.JTable tabelDataMatakuliah;
    // End of variables declaration                   
}
