/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Perkuliahan extends javax.swing.JFrame {


    public Perkuliahan() {
        initComponents();
        connectAndFillTable(); // Memanggil fungsi untuk mengisi tabel
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
    }
    private void connectAndFillTable() {
    String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda

    String query = "SELECT Nim, Kode_MK, Nip, Nilai FROM perkuliahan";

    try {
        Connection conn = DriverManager.getConnection(url, user, password);
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        // Model tabel untuk menampung data dari database
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Bersihkan tabel sebelum mengisi

        while (rs.next()) {
            // Tambahkan baris ke model tabel
            model.addRow(new Object[]{
                rs.getString("Nim"),
                rs.getString("Kode_MK"),
                rs.getString("Nip"),
                rs.getString("Nilai")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal menghubungkan ke database: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMatakuliah = new javax.swing.JLabel();
        btnDosen = new javax.swing.JLabel();
        btnMahasiswa = new javax.swing.JLabel();
        btnPerkuliahan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JDataPerkuliahan = new javax.swing.JLabel();
        JNim = new javax.swing.JLabel();
        jtfNim = new javax.swing.JTextField();
        JKodeMatakuliah = new javax.swing.JLabel();
        JNip = new javax.swing.JLabel();
        jtfKodeMatakuliah = new javax.swing.JTextField();
        jtfNip = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        JNilai = new javax.swing.JLabel();
        jtfNilai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 112, 107));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnMatakuliah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMatakuliah.setForeground(new java.awt.Color(255, 255, 255));
        btnMatakuliah.setText("Matakuliah");
        btnMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMatakuliahMouseClicked(evt);
            }
        });

        btnDosen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnDosen.setText("Dosen");
        btnDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDosenMouseClicked(evt);
            }
        });

        btnMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnMahasiswa.setText("Mahasiswa");
        btnMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMahasiswaMouseClicked(evt);
            }
        });

        btnPerkuliahan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPerkuliahan.setForeground(new java.awt.Color(255, 255, 255));
        btnPerkuliahan.setText("Perkuliahan");
        btnPerkuliahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerkuliahanMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("____________");

        btnLogout.setBackground(new java.awt.Color(204, 51, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMatakuliah)
                            .addComponent(btnDosen)
                            .addComponent(btnMahasiswa)
                            .addComponent(btnPerkuliahan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnLogout)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addComponent(btnMatakuliah)
                .addGap(18, 18, 18)
                .addComponent(btnDosen)
                .addGap(18, 18, 18)
                .addComponent(btnMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(btnPerkuliahan)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nim", "Kode Matakuliah", "Nip", "Nilai"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        JDataPerkuliahan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JDataPerkuliahan.setForeground(new java.awt.Color(0, 112, 107));
        JDataPerkuliahan.setText("Data Perkuliahan");

        JNim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JNim.setText("Nim");

        jtfNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNimActionPerformed(evt);
            }
        });

        JKodeMatakuliah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JKodeMatakuliah.setText("Kode Matakuliah");

        JNip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JNip.setText("Nip");

        jtfKodeMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKodeMatakuliahActionPerformed(evt);
            }
        });

        jtfNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNipActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 204, 51));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        JNilai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JNilai.setText("Nilai");

        jtfNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNilaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1)
                            .addComponent(JDataPerkuliahan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JNim)
                                    .addComponent(jtfNim, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JNilai)
                                    .addComponent(jtfNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfKodeMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JKodeMatakuliah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JNip)
                                    .addComponent(jtfNip, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(271, 271, 271))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDataPerkuliahan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNim)
                    .addComponent(JKodeMatakuliah)
                    .addComponent(JNip))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfKodeMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JNilai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void jtfNimActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jtfKodeMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void jtfNipActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String nim = jtfNim.getText();
        String kodeMK = jtfKodeMatakuliah.getText();
        String nip = jtfNip.getText();
        String nilai = jtfNilai.getText();

        if (nim.isEmpty() || kodeMK.isEmpty() || nip.isEmpty() || nilai.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
            return;
        }
    
        String url = "jdbc:mysql://localhost:3306/db_akademik";
        String user = "root"; // Ganti dengan username database Anda
        String password = ""; // Ganti dengan password database Anda
    
        String query = "UPDATE perkuliahan SET Kode_MK = ?, Nip = ?, Nilai = ? WHERE Nim = ?";
    
        try (Connection conn = DriverManager.getConnection(url, user, password);
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setString(1, kodeMK);
            pstmt.setString(2, nip);
            pstmt.setString(3, nilai);
            pstmt.setString(4, nim);
            
            int affectedRows = pstmt.executeUpdate();
            
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
                connectAndFillTable(); // Memperbarui tabel
            } else {
                JOptionPane.showMessageDialog(null, "Data gagal diperbarui");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menghubungkan ke database: " + e.getMessage());
        }
        clearData();
    }                                       


    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String nim = jtfNim.getText();
    String kodeMK = jtfKodeMatakuliah.getText();
    String nip = jtfNip.getText();
    String nilai = jtfNilai.getText();

    if (nim.isEmpty() || kodeMK.isEmpty() || nip.isEmpty() || nilai.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
        return;
    }

    String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda

    String query = "INSERT INTO perkuliahan (Nim, Kode_MK, Nip, Nilai) VALUES (?, ?, ?, ?)";

    try (Connection conn = DriverManager.getConnection(url, user, password);
         PreparedStatement pstmt = conn.prepareStatement(query)) {
        
        pstmt.setString(1, nim);
        pstmt.setString(2, kodeMK);
        pstmt.setString(3, nip);
        pstmt.setString(4, nilai);
        
        int affectedRows = pstmt.executeUpdate();
        
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
            connectAndFillTable(); // Memperbarui tabel
        } else {
            JOptionPane.showMessageDialog(null, "Data gagal ditambahkan");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menghubungkan ke database: " + e.getMessage());
    }
    clearData();
    }                                         


    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String nim = jtfNim.getText(); // Mengambil NIM dari text field

        if (nim.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
            return;
        }

    String url = "jdbc:mysql://localhost:3306/db_akademik";
    String user = "root"; // Ganti dengan username database Anda
    String password = ""; // Ganti dengan password database Anda

    String query = "DELETE FROM perkuliahan WHERE Nim = ?";

    try (Connection conn = DriverManager.getConnection(url, user, password);
         PreparedStatement pstmt = conn.prepareStatement(query)) {
        
        pstmt.setString(1, nim);
        
        int affectedRows = pstmt.executeUpdate();
        
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            connectAndFillTable(); // Memperbarui tabel
        } else {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menghubungkan ke database: " + e.getMessage());
    }
    clearData();
    }                                        

    private void jtfNilaiActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnMatakuliahMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        Matakuliah matakuliah = new Matakuliah();
        matakuliah.setVisible(true);
        this.dispose();
    }                                          


    private void btnDosenMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        Dosen dosen = new Dosen();
        dosen.setVisible(true);
        this.dispose();

    }                                     


    private void btnMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        Mahasiswa mahasiswa = new Mahasiswa();
        mahasiswa.setVisible(true);
        this.dispose();
    }                                         

    private void btnPerkuliahanMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }                                      

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }
    private void clearData() {
        jtfNim.setText("");
        jtfKodeMatakuliah.setText("");
        jtfNip.setText("");
        jtfNilai.setText("");
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // Mendapatkan model dari tabel
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
        // Mendapatkan baris yang dipilih
        int selectedRowIndex = jTable1.getSelectedRow();
    
        // Mengatur nilai dari tabel ke field teks
        jtfNim.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jtfKodeMatakuliah.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jtfNip.setText(model.getValueAt(selectedRowIndex, 2).toString());
        jtfNilai.setText(model.getValueAt(selectedRowIndex, 3).toString());
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perkuliahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perkuliahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perkuliahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perkuliahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perkuliahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel JDataPerkuliahan;
    private javax.swing.JLabel JKodeMatakuliah;
    private javax.swing.JLabel JNilai;
    private javax.swing.JLabel JNim;
    private javax.swing.JLabel JNip;
    private javax.swing.JLabel btnDosen;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel btnMahasiswa;
    private javax.swing.JLabel btnMatakuliah;
    private javax.swing.JLabel btnPerkuliahan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtfKodeMatakuliah;
    private javax.swing.JTextField jtfNilai;
    private javax.swing.JTextField jtfNim;
    private javax.swing.JTextField jtfNip;
    // End of variables declaration                   
}
